### ISSUE TITLE
재홍님 피드백 전달 드립니다 :)

### ISSUE THREAD

**Issue by hochan9** [mocha-rm/scheduler-develop#1]
# 좋은점
- 생성자를 통해 User 와 Schedule 이 필수값으로 들어올 수 있게 해주신 것 정말 잘하셨습니다.
- 피드백 드린대로 java doc 을 잘 작성해주신 것 같네요.
- 엔티티에 컬럼의 사이즈를 명명해주신 점도 좋은것같아요.
- 댓글 조회 시에 스케줄을 먼저 조회해서 schedule 검증해주신 점도 좋았습니다.
# 아쉬운점
- RuntimeException 보단 커스텀 Exception 으로 관리하는 것도 괜찮지 않나 싶습니다. -> 혹은 default 에 작성하신 것처럼 일관성 있는것이 좋을 것 같아요
- JPA 에서 `Comment()` 이 빈생성자가 필요한데, 개인적으로 protected 로 구성하시면 좋지 않을까 싶습니다.
- 트랜잭션 범위도 한번 고민해보시는 것도 좋을 것 같네요.
- Valid 를 하다 만 느낌이 강하네요
- javadoc 을 작성하긴하셨지만, 이것도 쓰다 만 느낌이 다소있습니다 ㅠ
# 추가사항
- collect 와 toList 의 차이점이 있길래 공유드립니다.
- [Stream.toList로 Stream.collect(toList()를 대체해도 되는 걸까?](https://binux.tistory.com/146)

**Comment by mocha-rm** [comment]
넵 ! 다음엔 조금 더 신경 써 보도록 하겠습니다 ! 피드백 감사합니다.
